### ISSUE TITLE
Support for Next.js?

### ISSUE THREAD

**Issue by shelbyd** [benchsci/rules_nodejs_gazelle#33]
[This page](https://github.com/bazelbuild/bazel-gazelle#supported-languages) claims that this project supports Next.js (and other bundlers). I'm trying to integrate this into my (closed source) project, and my gazelle command isn't able to import `styles`. It's possible I've missed something, or that Next.js support isn't implemented yet.

If Next.js support is planned, I suppose this can be a tracking issue for it. If I can get an idea of what would be required, I might implement it myself.

If this is already supported, then we should add some docs to the main Readme.

If it's never planned to be supported, then we should update the `bazel-gazelle` docs accordingly.

**Comment by ColinHeathman** [comment]
@shelbyd The linked PR is some WIP towards rule generation for a Next.JS app

In the meantime it's possible to get Next.JS or other bundlers to work using a macro like this:
https://github.com/aspect-build/bazel-examples/blob/main/next.js/bazel/next.bzl

**Comment by ColinHeathman** [comment]
The [latest release](https://github.com/benchsci/rules_nodejs_gazelle/releases/tag/v0.4.0) has an end-to-end example on a NextJS app built with Bazel in the `examples` folder
