### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by KlotzAndrew** [benchsci/rules_nodejs_gazelle#42]
Any plans to cut a new release?

The example project does not work with the current v0.3.0 release. It does work when run using the main branch and a `local_repository`.

To reproduce:
 - pull the repo
 - swap the [local_repository](https://github.com/benchsci/rules_nodejs_gazelle/blob/main/examples/nextjs/WORKSPACE#L107-L110) with an [http_archive](https://github.com/benchsci/rules_nodejs_gazelle/blob/main/examples/nextjs/WORKSPACE#L98-L106) of the [latest relase](https://github.com/benchsci/rules_nodejs_gazelle/releases/tag/v0.3.0) (v0.3.0)
 -  run `bazel run //:gazelle` and see errors

The first error has to do with the [js_package_file directive](https://github.com/benchsci/rules_nodejs_gazelle/blob/main/examples/nextjs/BUILD.bazel#L12) unable to opeb the file `<dir>/package.json :node_modules`. I think it is missing the commit [parsing the second argument to that directive](https://github.com/benchsci/rules_nodejs_gazelle/blob/main/gazelle/configure.go#L293-L297) added since v0.3.0

I tried removing the second argument (`:node_modules`) from the js_package_file directive, but got another error. `web_assets` function not found. Maybe for similar reasons, code added since the v0.3.0 release?

**Comment by ColinHeathman** [comment]
Hi @KlotzAndrew, yes we are planning to release 0.4.0 very soon! I'll write a note here when we do

**Comment by ColinHeathman** [comment]
The [new release](https://github.com/benchsci/rules_nodejs_gazelle/releases/tag/v0.4.0) has been published
