### ISSUE TITLE
Releases are still not available in BCR

### ISSUE THREAD

**Issue by wingsofovnia** [benchsci/rules_nodejs_gazelle#57]
Although #54 has been resolved and [release v0.6.0](https://github.com/benchsci/rules_nodejs_gazelle/releases/tag/v0.6.0) provides a snippet for consumption in `MODULE.bazel`, `com_github_benchsci_rules_nodejs_gazelle` is still not available in BCR.

```
bazel run //:gazelle.update
ERROR: Error computing the main repository mapping: in module dependency chain \
  <root> -> com_github_benchsci_rules_nodejs_gazelle@0.6.0: module not found in registries: com_github_benchsci_rules_nodejs_gazelle@0.6.0
```

and also no resolvable in BCR UI: https://registry.bazel.build/search?q=com_github_benchsci_rules_nodejs_gazelle

**Comment by ewianda** [comment]
Now available
