### ISSUE TITLE
Should we make `package.json` optional

### ISSUE THREAD

**Issue by ewianda** [benchsci/rules_nodejs_gazelle#9]
Just wondering if we should make reading deps from package.json optional. Trying to add a simple test case and noticed that `package.json` is required.

**Comment by ColinHeathman** [comment]
`package.json` could be optional, but Gazelle won't be able to generate `@npm//` imports without it. I think there are valid use cases for npm projects like that.

**Comment by ColinHeathman** [comment]
This is solved by https://github.com/benchsci/rules_nodejs_gazelle/pull/12
